import os
import time

# application header
APP_HEADER = '## Automatically generated by HostBlocker\n'

# info to use when building SOA DNS records
SOA_MNAME_VAR = 'HOSTBLOCKER_SOA_MNAME'
SOA_MNAME = os.getenv(SOA_MNAME_VAR, 'localhost.')
SOA_RNAME_VAR = 'HOSTBLOCKER_SOA_RNAME'
SOA_RNAME = os.getenv(SOA_RNAME_VAR, 'root.localhost.')
SOA_SERIAL_VAR = 'HOSTBLOCKER_SOA_SERIAL'
SOA_SERIAL = time.strftime('%Y%m%d%H', time.gmtime())
SOA_REFRESH_VAR = 'HOSTBLOCKER_SOA_REFRESH'
SOA_REFRESH = os.getenv(SOA_REFRESH_VAR, '172800')
SOA_RETRY_VAR = 'HOSTBLOCKER_SOA_RETRY'
SOA_RETRY = os.getenv(SOA_RETRY_VAR, '86400')
SOA_EXPIRE_VAR = 'HOSTBLOCKER_SOA_EXPIRE'
SOA_EXPIRE = os.getenv(SOA_EXPIRE_VAR, '1209600')
SOA_TTL_VAR = 'HOSTBLOCKER_SOA_TTL'
SOA_TTL = os.getenv(SOA_TTL_VAR, '86400')
SOA_DATA = ' SOA {} {} {} {} {} {} {}'.format(SOA_MNAME, SOA_RNAME,
                                              SOA_SERIAL,
                                              SOA_REFRESH, SOA_RETRY, SOA_EXPIRE, SOA_TTL)