import os
import time

from typing import Final


# application header
APP_HEADER: Final[str] = '## Automatically generated by HostBlocker\n'

# info to use when building SOA DNS records
SOA_MNAME_VAR: Final[str] = 'HOSTBLOCKER_SOA_MNAME'
SOA_MNAME: Final[str] = os.getenv(SOA_MNAME_VAR, 'localhost.')
SOA_RNAME_VAR: Final[str] = 'HOSTBLOCKER_SOA_RNAME'
SOA_RNAME: Final[str] = os.getenv(SOA_RNAME_VAR, 'root.localhost.')
SOA_SERIAL_VAR: Final[str] = 'HOSTBLOCKER_SOA_SERIAL'
SOA_SERIAL: Final[str] = time.strftime('%Y%m%d%H', time.gmtime())
SOA_REFRESH_VAR: Final[str] = 'HOSTBLOCKER_SOA_REFRESH'
SOA_REFRESH: Final[str] = os.getenv(SOA_REFRESH_VAR, '172800')
SOA_RETRY_VAR: Final[str] = 'HOSTBLOCKER_SOA_RETRY'
SOA_RETRY: Final[str] = os.getenv(SOA_RETRY_VAR, '86400')
SOA_EXPIRE_VAR: Final[str] = 'HOSTBLOCKER_SOA_EXPIRE'
SOA_EXPIRE: Final[str] = os.getenv(SOA_EXPIRE_VAR, '1209600')
SOA_TTL_VAR: Final[str] = 'HOSTBLOCKER_SOA_TTL'
SOA_TTL: Final[str] = os.getenv(SOA_TTL_VAR, '86400')
SOA_DATA: Final[str] = f' SOA {SOA_MNAME} {SOA_RNAME} {SOA_SERIAL} {SOA_REFRESH} {SOA_RETRY} {SOA_EXPIRE} {SOA_TTL}'
